name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: "Add CompatHelper"
        run: |
          import Pkg
          Pkg.add("CompatHelper")
        shell: julia --color=yes {0}

      - name: "Run CompatHelper"
        run: |
          import CompatHelper
          CompatHelper.main(; subdirs=["", "docs", "test"])
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
